import Icon from '../components/common/Icon'
import { formatDate } from '../utils/date'
import { isExamCompleted, isExamLocked, isExamOngoing } from '../utils/exam'

export default function ExamDetailPage({ exam, onBack, onStart }) {
  const completed = isExamCompleted(exam)
  const ongoing = isExamOngoing(exam)
  const locked = isExamLocked(exam)
  const statusLabel = locked ? 'TERKUNCI' : completed ? 'SELESAI' : ongoing ? 'SEDANG DIKERJAKAN' : 'TERSEDIA'
  return <div className="page-enter detail-page"><button className="back-button" onClick={onBack}>? Kembali ke ujian saya</button><div className="detail-hero"><div className={`large-subject-icon ${exam?.color}`}><Icon name="clipboard" size={30} /></div><div><span className={`status-pill ${locked ? 'locked' : completed ? 'completed' : ongoing ? 'ongoing' : 'available'}`}>{statusLabel}</span><h1>{exam?.title}</h1><p className="muted">Informasi dan status ujian berdasarkan data terbaru dari server.</p></div></div><div className="detail-layout"><div className="section-card detail-info"><h2>Informasi ujian</h2><div className="info-grid"><InfoItem label="Jadwal mulai" value={`${formatDate(exam?.start_time)} · 08.00 WIB`} /><InfoItem label="Durasi pengerjaan" value={`${exam?.duration_minutes} menit`} /><InfoItem label="Jumlah soal" value={`${exam?.total_questions} soal`} /><InfoItem label="Status" value={locked ? 'Terkunci' : completed ? 'Selesai' : ongoing ? 'Sedang dikerjakan' : 'Belum dimulai'} /></div><div className="notice-box"><span>?</span><div><strong>{locked ? 'Ujian terkunci' : completed ? 'Ujian telah selesai' : ongoing ? 'Kamu masih memiliki ujian aktif' : 'Pastikan kamu sudah siap'}</strong><p>{locked ? 'Ujian tidak dapat dilanjutkan karena akses telah dikunci.' : completed ? 'Jawaban sudah dikunci dan tidak dapat diubah.' : 'Waktu berjalan mengikuti server saat ujian dimulai.'}</p></div></div></div><div className="section-card start-card">{locked ? <><div className="start-card-top"><span className="small-label">AKSES DITOLAK</span><div className="start-illustration locked-mark">!</div></div><h2>Ujian tidak dapat dilanjutkan.</h2><p className="muted">Hubungi pengawas atau administrator jika menurutmu ini adalah kesalahan.</p></> : completed ? <><div className="start-card-top"><span className="small-label">UJIAN SELESAI</span><div className="start-illustration">?</div></div><h2>Hasil sudah tersedia.</h2><p className="muted">Buka halaman hasil untuk melihat nilai ujian.</p><button className="primary-button wide" onClick={() => onStart('result')}>Lihat hasil <Icon name="arrow" size={17} /></button></> : <><div className="start-card-top"><span className="small-label">{ongoing ? 'LANJUTKAN UJIAN?' : 'SIAP UNTUK MULAI?'}</span><div className="start-illustration">?</div></div><h2>{ongoing ? 'Lanjutkan pengerjaan.' : 'Kerjakan dengan percaya diri.'}</h2><p className="muted">Cari tempat yang tenang dan pastikan koneksi internetmu stabil.</p><button className="primary-button wide" onClick={onStart}>{ongoing ? 'Lanjutkan ujian' : 'Mulai ujian'} <Icon name="arrow" size={17} /></button></>}</div></div></div>
}

function InfoItem({ label, value }) {
  return <div className="info-item"><span>{label}</span><strong>{value}</strong></div>
}
