import { useState } from 'react'
import Icon from '../components/common/Icon'
import { formatDate } from '../utils/date'
import { isExamCompleted, isExamLocked, isExamOngoing } from '../utils/exam'

export default function ExamListPage({ exams, onExam, onExplanation }) {
  const [filter, setFilter] = useState('all')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(6)
  const filteredExams = exams.filter((exam) => filter === 'all' || filter === 'completed' && isExamCompleted(exam) || filter === 'ongoing' && isExamOngoing(exam) || filter === 'not_started' && !isExamCompleted(exam) && !isExamOngoing(exam))
  const totalPages = Math.max(1, Math.ceil(filteredExams.length / pageSize))
  const visibleExams = filteredExams.slice((page - 1) * pageSize, page * pageSize)
  const updateFilter = (value) => { setFilter(value); setPage(1) }
  const updatePageSize = (value) => { setPageSize(Number(value)); setPage(1) }
  const labels = { all: 'Semua status', completed: 'Selesai', ongoing: 'Sedang dikerjakan', not_started: 'Belum dimulai' }
  return <div className="page-enter"><div className="page-title-row"><div><p className="eyebrow">AKADEMIK</p><h1>Ujian saya</h1><p className="muted">Kelola dan kerjakan semua ujianmu di sini.</p></div><div className="filter-actions"><label className="filter-button"><Icon name="filter" size={15} /><select value={filter} onChange={(event) => updateFilter(event.target.value)} aria-label="Filter status ujian">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Icon name="chevronDown" size={14} /></label></div></div><div className="exam-list">{visibleExams.length ? visibleExams.map((exam) => { const completed = isExamCompleted(exam); const ongoing = isExamOngoing(exam); const locked = isExamLocked(exam); const showExplanation = exam.show_explanation === true || exam.show_explanation === 1 || exam.show_explanation === '1' || exam.show_explanation === 'true'; return <div className="list-exam-card" key={exam.id}><div className={`large-subject-icon ${exam.color}`}><Icon name="clipboard" size={25} /></div><div className="list-exam-content"><div className="list-top"><span className={`status-pill ${locked ? 'locked' : completed ? 'completed' : ongoing ? 'ongoing' : exam.status}`}>{locked ? 'Terkunci' : completed ? 'Selesai' : ongoing ? 'Sedang dikerjakan' : 'Tersedia'}</span><span className="list-code">ID {exam.id}</span></div><h2>{exam.title}</h2><p className="muted">{exam.subject || 'Ujian'} • {exam.total_questions} soal • {exam.duration_minutes} menit</p><div className="exam-progress"><div><span>Jadwal ujian</span><strong>{formatDate(exam.start_time)} · 08.00 WIB</strong></div>{completed ? <div className="mini-score"><span>Nilai</span><strong>{exam.final_score ?? '—'}</strong></div> : locked ? <span className="locked-hint">Ujian tidak dapat dilanjutkan</span> : <button className="primary-button small" onClick={() => onExam(exam)}>{ongoing ? 'Lanjutkan' : 'Lihat detail'} <Icon name="arrow" size={15} /></button>}</div>{completed && showExplanation && <button type="button" className="explanation-link-button" onClick={() => onExplanation(exam)}><Icon name="book" size={15} /> Lihat pembahasan</button>}</div></div> }) : <div className="empty-state">Tidak ada ujian dengan status “{labels[filter]}”.</div>}</div>{filteredExams.length > 0 && <div className="exam-pagination"><label>Item per halaman <select value={pageSize} onChange={(event) => updatePageSize(event.target.value)}><option value="6">6</option><option value="10">10</option><option value="20">20</option></select></label><span>Halaman {page} dari {totalPages}</span><div><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Sebelumnya</button><button type="button" disabled={page === totalPages} onClick={() => setPage((value) => value + 1)}>Berikutnya</button></div></div>}</div>
}
